### ISSUE TITLE
Client/server example?

### ISSUE THREAD

**Issue by aafanasyev** [plizonczyk/noiseprotocol#11]
Any full client server example in readme  should help a lot...

**Comment by aafanasyev** [comment]
Dear Piotr,

I am trying to create a server according your main example. However, I believe my code is missing something:
```python
#!/usr/bin/env python

import socket
from noise.builder import NoiseBuilder

host = '127.0.1.1'  
port = 8888
payload = 1500
server_address = (host, port)

def start_TCP_server():
    proto = NoiseBuilder.from_name(b'Noise_NN_25519_ChaChaPoly_SHA256')
    proto.get_handshake_hash()
    proto.set_as_responder()
    proto.start_handshake()
    
    message = proto.write_message()

    socket_Noise = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    socket_Noise.bind(server_address)
    socket_Noise.listen(1)

    print("Noise server is running...")

    while True:    
        client, client_address = socket_Noise.accept()
        print(client_address)

        while True:
            data = client.recv(payload)
            if not data: 
                break
            client.sendall(data)

if __name__ == "__main__":
    start_TCP_server()
```
May you help me out? 

Thank you.

**Comment by plizonczyk** [comment]
Hello Andrey,
I've updated the readme in trunk branch of the repository: https://github.com/plizonczyk/noiseprotocol/tree/trunk

Regarding the code snippet you've pasted:

1. proto.get_handshake_hash() statement has no effect
2. you can't write message before reading a message from initiator if in the responder role - NoiseBuilder would raise a NoiseHandshakeError in this case.
```
Traceback (most recent call last):
...
noise.exceptions.NoiseHandshakeError: NoiseBuilder.read_message has to be called now
```
3. you need to use _proto_ you've created to encrypt data sent to the other party. So, instead of `client.sendall(data)` you should use `client.sendall(proto.write_message(data))`. By the way, you need to feed the data received from the initiator into _proto_ first in order to decrypt it - so after `data = client.recv(payload)` you should do `plaintext = proto.read_message(data)`.
4. after finishing handshake (in case of this pattern (NN) - after one cycle of read/write) - you should use _proto.encrypt_ and _proto.decrypt_.

If you won't be able to figure it out based on the updated readme - please let me know and we'll fix up your code.

Kind regards,
Piotr
